n = int(input('Digite um valor para saber sua tabuada: '))
print(f'A tabuada desse numero é:')
print('_'*15)
print(f'{1:2} x {n} = {n:}')
print(f'{2:2} x {n} = {n*2:}')
print(f'{3:2} x {n} = {n*3:}')
print(f'{4:2} x {n} = {n*4:}')
print(f'{5:2} x {n} = {n*5:}')
print(f'{6:2} x {n} = {n*6:}')
print(f'{7:2} x {n} = {n*7:}')
print(f'{8:2} x {n} = {n*8:}')
print(f'{9:2} x {n} = {n*9:}')
print(f'{10:2} x {n} = {n*10}')
print('_'*15)
