a = input('Digite algo: ')
print('Só tem espaços? ',a.isspace())
print('É alfanumérico? ', a.isalnum())
print('É numerico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('Está maiusculo? ',a.isupper())
print('Está minusculo? ', a.islower())
print('Está capitalizada? ', a.istitle())
print('Essa variavel é do tipo primitivo: ', type(a))
