nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome em maiúsculo é: {nome.upper()}.')
print(f'Seu nome em minusculo é: {nome.lower()}.')
letras = nome.split()
print(f'Seu nome tem {len(nome)-nome.count(" ")} letras ao todo.')
print(f'Seu primeiro nome é {letras[0]} tem {len(letras[0])} letras.')
